DEBUG - 2025-10-29 16:07:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-10-29 16:07:34 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/register.php"
[Method: GET, Route: register]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/register.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/register', [], true)
 3 APPPATH\Controllers\Auth.php(70): view('auth/register')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-10-29 16:08:06 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'diagnosa-jantung' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'diagnosa-jantun...', 3306, '', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\diagnosa-jantung\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(36): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
#8 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'diagnosa-jantung' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\diagnosa-jantung\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\diagnosa-jantung\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(36): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
#7 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-10-29 16:08:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'diagnosa-jantung'
[Method: POST, Route: auth/attemptLogin]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(715): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(36): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-29 16:09:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:09:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-10-29 16:09:50 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/register.php"
[Method: GET, Route: register]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/register.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/register', [], true)
 3 APPPATH\Controllers\Auth.php(70): view('auth/register')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-10-29 16:10:39 --> mysqli_sql_exception: Unknown column 'email' in 'field list' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\app\Database\Seeds\AdminSeeder.php(19): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\laragon\www\diagnosa-jantung\system\Database\Seeder.php(149): App\Database\Seeds\AdminSeeder->run()
#6 C:\laragon\www\diagnosa-jantung\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
ERROR - 2025-10-29 16:13:38 --> mysqli_sql_exception: Duplicate entry 'admin' for key 'users.username' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\app\Database\Seeds\AdminSeeder.php(19): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\laragon\www\diagnosa-jantung\system\Database\Seeder.php(149): App\Database\Seeds\AdminSeeder->run()
#6 C:\laragon\www\diagnosa-jantung\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-10-29 16:13:52 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/register.php"
[Method: GET, Route: register]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/register.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/register', [], true)
 3 APPPATH\Controllers\Auth.php(70): view('auth/register')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:13:53 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/register.php"
[Method: GET, Route: register]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/register.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/register', [], true)
 3 APPPATH\Controllers\Auth.php(70): view('auth/register')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:13:54 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/register.php"
[Method: GET, Route: register]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/register.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/register', [], true)
 3 APPPATH\Controllers\Auth.php(70): view('auth/register')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-29 16:13:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:14:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:14:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:14:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-29 16:17:15 --> mysqli_sql_exception: Duplicate entry 'admin' for key 'users.username' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\app\Database\Seeds\AdminSeeder.php(19): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\laragon\www\diagnosa-jantung\system\Database\Seeder.php(149): App\Database\Seeds\AdminSeeder->run()
#6 C:\laragon\www\diagnosa-jantung\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
DEBUG - 2025-10-29 16:17:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:17:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:17:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:20:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:20:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:20:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:20:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-29 16:27:44 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\app\Database\Seeds\AdminSeeder.php(22): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\laragon\www\diagnosa-jantung\system\Database\Seeder.php(149): App\Database\Seeds\AdminSeeder->run()
#6 C:\laragon\www\diagnosa-jantung\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
DEBUG - 2025-10-29 16:29:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:29:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 16:29:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-29 16:29:15 --> mysqli_sql_exception: Unknown column 'last_login' in 'field list' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\laragon\www\diagnosa-jantung\system\BaseModel.php(1025): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\laragon\www\diagnosa-jantung\system\Model.php(860): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(61): CodeIgniter\Model->update('2', Array)
#8 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
#9 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-10-29 16:29:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'last_login' in 'field list'
[Method: POST, Route: auth/attemptLogin]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `last_login` = :last_login:, `updated_at` = :updated_at:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Auth.php(61): CodeIgniter\Model->update('2', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:29:15 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'last_login' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `last_login` = \'2025-10-29 16:29:15\', `updated_at` = \'2025-10-29 16:29:15\'
WHERE `users`.`id` IN (\'2\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `last_login` = \'2025-10-29 16:29:15\', `updated_at` = \'2025-10-29 16:29:15\'
WHERE `users`.`id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `last_login` = :last_login:, `updated_at` = :updated_at:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Auth.php(61): CodeIgniter\Model->update('2', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:29:15 --> [Caused by] mysqli_sql_exception: Unknown column 'last_login' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `last_login` = \'2025-10-29 16:29:15\', `updated_at` = \'2025-10-29 16:29:15\'
WHERE `users`.`id` IN (\'2\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `last_login` = \'2025-10-29 16:29:15\', `updated_at` = \'2025-10-29 16:29:15\'
WHERE `users`.`id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `last_login` = \'2025-10-29 16:29:15\', `updated_at` = \'2025-10-29 16:29:15\'
WHERE `users`.`id` IN (\'2\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `last_login` = :last_login:, `updated_at` = :updated_at:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Auth.php(61): CodeIgniter\Model->update('2', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-10-29 16:33:38 --> mysqli_sql_exception: Unknown column 'last_login' in 'field list' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\laragon\www\diagnosa-jantung\system\BaseModel.php(1025): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\laragon\www\diagnosa-jantung\system\Model.php(860): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(61): CodeIgniter\Model->update('2', Array)
#8 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
#9 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-10-29 16:33:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'last_login' in 'field list'
[Method: POST, Route: auth/attemptLogin]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `last_login` = :last_login:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Auth.php(61): CodeIgniter\Model->update('2', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:33:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'last_login' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `last_login` = \'2025-10-29 16:33:38\'
WHERE `users`.`id` IN (\'2\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `last_login` = \'2025-10-29 16:33:38\'
WHERE `users`.`id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `last_login` = :last_login:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Auth.php(61): CodeIgniter\Model->update('2', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:33:38 --> [Caused by] mysqli_sql_exception: Unknown column 'last_login' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `last_login` = \'2025-10-29 16:33:38\'
WHERE `users`.`id` IN (\'2\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `last_login` = \'2025-10-29 16:33:38\'
WHERE `users`.`id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `last_login` = \'2025-10-29 16:33:38\'
WHERE `users`.`id` IN (\'2\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `last_login` = :last_login:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Auth.php(61): CodeIgniter\Model->update('2', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-29 16:33:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-29 16:33:45 --> mysqli_sql_exception: Unknown column 'last_login' in 'field list' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\laragon\www\diagnosa-jantung\system\BaseModel.php(1025): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\laragon\www\diagnosa-jantung\system\Model.php(860): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(61): CodeIgniter\Model->update('2', Array)
#8 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
#9 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-10-29 16:33:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'last_login' in 'field list'
[Method: POST, Route: auth/attemptLogin]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `last_login` = :last_login:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Auth.php(61): CodeIgniter\Model->update('2', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:33:45 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'last_login' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `last_login` = \'2025-10-29 16:33:45\'
WHERE `users`.`id` IN (\'2\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `last_login` = \'2025-10-29 16:33:45\'
WHERE `users`.`id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `last_login` = :last_login:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Auth.php(61): CodeIgniter\Model->update('2', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:33:45 --> [Caused by] mysqli_sql_exception: Unknown column 'last_login' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `last_login` = \'2025-10-29 16:33:45\'
WHERE `users`.`id` IN (\'2\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `last_login` = \'2025-10-29 16:33:45\'
WHERE `users`.`id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `last_login` = \'2025-10-29 16:33:45\'
WHERE `users`.`id` IN (\'2\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `last_login` = :last_login:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Auth.php(61): CodeIgniter\Model->update('2', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptLogin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:35:10 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/register.php"
[Method: GET, Route: register]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/register.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/register', [], true)
 3 APPPATH\Controllers\Auth.php(72): view('auth/register')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-29 16:39:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-29 16:39:54 --> mysqli_sql_exception: Unknown column 'nik' in 'where clause' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\diagnosa-jantung\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('123893892783432...', 'pasien.nik', Array)
#6 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('123893892783432...', 'pasien.nik', Array, NULL, 'nik')
#7 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '123893892783432...', Array, Array, 'nik')
#8 C:\laragon\www\diagnosa-jantung\system\Controller.php(138): CodeIgniter\Validation\Validation->run()
#9 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(91): CodeIgniter\Controller->validate(Array)
#10 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
#11 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#14 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#15 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#16 {main}
CRITICAL - 2025-10-29 16:39:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nik' in 'where clause'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 4 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 5 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 6 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:39:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nik' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 6 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 7 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 8 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:39:54 --> [Caused by] mysqli_sql_exception: Unknown column 'nik' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 7 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 8 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 9 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
10 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
11 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
12 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
13 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
16 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-10-29 16:44:11 --> mysqli_sql_exception: Unknown column 'nik' in 'where clause' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\diagnosa-jantung\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('123893892783432...', 'pasien.nik', Array)
#6 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('123893892783432...', 'pasien.nik', Array, NULL, 'nik')
#7 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '123893892783432...', Array, Array, 'nik')
#8 C:\laragon\www\diagnosa-jantung\system\Controller.php(138): CodeIgniter\Validation\Validation->run()
#9 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(91): CodeIgniter\Controller->validate(Array)
#10 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
#11 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#14 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#15 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#16 {main}
CRITICAL - 2025-10-29 16:44:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nik' in 'where clause'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 4 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 5 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 6 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:44:11 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nik' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 6 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 7 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 8 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:44:11 --> [Caused by] mysqli_sql_exception: Unknown column 'nik' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 7 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 8 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 9 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
10 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
11 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
12 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
13 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
16 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-10-29 16:44:15 --> mysqli_sql_exception: Unknown column 'nik' in 'where clause' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\diagnosa-jantung\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('123893892783432...', 'pasien.nik', Array)
#6 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('123893892783432...', 'pasien.nik', Array, NULL, 'nik')
#7 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '123893892783432...', Array, Array, 'nik')
#8 C:\laragon\www\diagnosa-jantung\system\Controller.php(138): CodeIgniter\Validation\Validation->run()
#9 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(91): CodeIgniter\Controller->validate(Array)
#10 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
#11 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#14 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#15 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#16 {main}
CRITICAL - 2025-10-29 16:44:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nik' in 'where clause'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 4 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 5 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 6 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:44:15 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nik' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 6 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 7 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 8 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:44:15 --> [Caused by] mysqli_sql_exception: Unknown column 'nik' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 7 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 8 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 9 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
10 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
11 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
12 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
13 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
16 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-29 16:44:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-29 16:44:27 --> mysqli_sql_exception: Unknown column 'nik' in 'where clause' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\diagnosa-jantung\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('123893892783432...', 'pasien.nik', Array)
#6 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('123893892783432...', 'pasien.nik', Array, NULL, 'nik')
#7 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '123893892783432...', Array, Array, 'nik')
#8 C:\laragon\www\diagnosa-jantung\system\Controller.php(138): CodeIgniter\Validation\Validation->run()
#9 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(91): CodeIgniter\Controller->validate(Array)
#10 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
#11 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#14 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#15 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#16 {main}
CRITICAL - 2025-10-29 16:44:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nik' in 'where clause'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 4 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 5 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 6 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:44:27 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nik' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 6 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 7 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 8 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:44:27 --> [Caused by] mysqli_sql_exception: Unknown column 'nik' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 7 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 8 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 9 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
10 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
11 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
12 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
13 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
16 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-10-29 16:44:33 --> mysqli_sql_exception: Unknown column 'nik' in 'where clause' in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\diagnosa-jantung\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('123893892783432...', 'pasien.nik', Array)
#6 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('123893892783432...', 'pasien.nik', Array, NULL, 'nik')
#7 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '123893892783432...', Array, Array, 'nik')
#8 C:\laragon\www\diagnosa-jantung\system\Controller.php(138): CodeIgniter\Validation\Validation->run()
#9 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(91): CodeIgniter\Controller->validate(Array)
#10 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
#11 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#14 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#15 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#16 {main}
CRITICAL - 2025-10-29 16:44:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nik' in 'where clause'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 4 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 5 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 6 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:44:33 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'nik' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 6 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 7 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 8 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 16:44:33 --> [Caused by] mysqli_sql_exception: Unknown column 'nik' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 7 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 8 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 9 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
10 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
11 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
12 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
13 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
16 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-10-29 16:45:23 --> mysqli_sql_exception: Can't DROP 'last_login'; check that column/key exists in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('ALTER TABLE `us...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('ALTER TABLE `us...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE `us...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\Forge.php(799): CodeIgniter\Database\BaseConnection->query('ALTER TABLE `us...')
#4 C:\laragon\www\diagnosa-jantung\app\Database\Migrations\2025-10-29-163020_AddLastLoginToUsers.php(22): CodeIgniter\Database\Forge->dropColumn('users', 'last_login')
#5 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(876): App\Database\Migrations\AddLastLoginToUsers->down()
#6 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(289): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 C:\laragon\www\diagnosa-jantung\system\Commands\Database\MigrateRollback.php(101): CodeIgniter\Database\MigrationRunner->regress(0)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-29 16:47:49 --> mysqli_sql_exception: Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'pasien_user_id_foreign' are incompatible. in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `p...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `p...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `p...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `p...')
#4 C:\laragon\www\diagnosa-jantung\app\Database\Migrations\2025-10-29-164108_AddPasienTable.php(78): CodeIgniter\Database\Forge->createTable('pasien')
#5 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(876): App\Database\Migrations\AddPasienTable->up()
#6 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\laragon\www\diagnosa-jantung\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-29 16:49:44 --> mysqli_sql_exception: Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'pasien_user_id_foreign' are incompatible. in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `p...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `p...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `p...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `p...')
#4 C:\laragon\www\diagnosa-jantung\app\Database\Migrations\2025-10-29-164108_AddPasienTable.php(78): CodeIgniter\Database\Forge->createTable('pasien')
#5 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(876): App\Database\Migrations\AddPasienTable->up()
#6 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\laragon\www\diagnosa-jantung\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-29 16:50:15 --> mysqli_sql_exception: Can't DROP 'last_login'; check that column/key exists in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('ALTER TABLE `us...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('ALTER TABLE `us...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE `us...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\Forge.php(799): CodeIgniter\Database\BaseConnection->query('ALTER TABLE `us...')
#4 C:\laragon\www\diagnosa-jantung\app\Database\Migrations\2025-10-29-163020_AddLastLoginToUsers.php(22): CodeIgniter\Database\Forge->dropColumn('users', 'last_login')
#5 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(876): App\Database\Migrations\AddLastLoginToUsers->down()
#6 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(289): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 C:\laragon\www\diagnosa-jantung\system\Commands\Database\MigrateRollback.php(101): CodeIgniter\Database\MigrationRunner->regress(0)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-29 16:50:43 --> mysqli_sql_exception: Can't DROP 'last_login'; check that column/key exists in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('ALTER TABLE `us...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('ALTER TABLE `us...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE `us...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\Forge.php(799): CodeIgniter\Database\BaseConnection->query('ALTER TABLE `us...')
#4 C:\laragon\www\diagnosa-jantung\app\Database\Migrations\2025-10-29-163020_AddLastLoginToUsers.php(22): CodeIgniter\Database\Forge->dropColumn('users', 'last_login')
#5 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(876): App\Database\Migrations\AddLastLoginToUsers->down()
#6 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(289): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 C:\laragon\www\diagnosa-jantung\system\Commands\Database\MigrateRollback.php(101): CodeIgniter\Database\MigrationRunner->regress(0)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 C:\laragon\www\diagnosa-jantung\system\CLI\BaseCommand.php(119): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 C:\laragon\www\diagnosa-jantung\system\Commands\Database\MigrateRefresh.php(86): CodeIgniter\CLI\BaseCommand->call('migrate:rollbac...', Array)
#11 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateRefresh->run(Array)
#12 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:refresh', Array)
#13 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#14 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#15 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#16 {main}
ERROR - 2025-10-29 16:50:43 --> mysqli_sql_exception: Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'pasien_user_id_foreign' are incompatible. in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `p...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `p...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `p...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `p...')
#4 C:\laragon\www\diagnosa-jantung\app\Database\Migrations\2025-10-29-164108_AddPasienTable.php(78): CodeIgniter\Database\Forge->createTable('pasien')
#5 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(876): App\Database\Migrations\AddPasienTable->up()
#6 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\laragon\www\diagnosa-jantung\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\laragon\www\diagnosa-jantung\system\CLI\BaseCommand.php(119): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\laragon\www\diagnosa-jantung\system\Commands\Database\MigrateRefresh.php(87): CodeIgniter\CLI\BaseCommand->call('migrate', Array)
#11 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateRefresh->run(Array)
#12 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:refresh', Array)
#13 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#14 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#15 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#16 {main}
ERROR - 2025-10-29 16:51:15 --> mysqli_sql_exception: Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'pasien_user_id_foreign' are incompatible. in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `p...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `p...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `p...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `p...')
#4 C:\laragon\www\diagnosa-jantung\app\Database\Migrations\2025-10-29-164108_AddPasienTable.php(78): CodeIgniter\Database\Forge->createTable('pasien')
#5 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(876): App\Database\Migrations\AddPasienTable->up()
#6 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\laragon\www\diagnosa-jantung\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-29 16:58:38 --> mysqli_sql_exception: Table 'users' already exists in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\laragon\www\diagnosa-jantung\app\Database\Migrations\2025-10-29-165400_CreateUsersTable.php(62): CodeIgniter\Database\Forge->createTable('users')
#5 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsersTable->up()
#6 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\laragon\www\diagnosa-jantung\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-29 16:58:43 --> mysqli_sql_exception: Table 'users' already exists in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\laragon\www\diagnosa-jantung\app\Database\Migrations\2025-10-29-165400_CreateUsersTable.php(62): CodeIgniter\Database\Forge->createTable('users')
#5 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsersTable->up()
#6 C:\laragon\www\diagnosa-jantung\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\laragon\www\diagnosa-jantung\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\laragon\www\diagnosa-jantung\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\laragon\www\diagnosa-jantung\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\laragon\www\diagnosa-jantung\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\laragon\www\diagnosa-jantung\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\laragon\www\diagnosa-jantung\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-29 17:00:32 --> mysqli_sql_exception: Table 'diagnosa_jantung.pasien' doesn't exist in C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\laragon\www\diagnosa-jantung\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\laragon\www\diagnosa-jantung\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\laragon\www\diagnosa-jantung\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\laragon\www\diagnosa-jantung\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\diagnosa-jantung\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('123893892783432...', 'pasien.nik', Array)
#6 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('123893892783432...', 'pasien.nik', Array, NULL, 'nik')
#7 C:\laragon\www\diagnosa-jantung\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '123893892783432...', Array, Array, 'nik')
#8 C:\laragon\www\diagnosa-jantung\system\Controller.php(138): CodeIgniter\Validation\Validation->run()
#9 C:\laragon\www\diagnosa-jantung\app\Controllers\Auth.php(91): CodeIgniter\Controller->validate(Array)
#10 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
#11 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 C:\laragon\www\diagnosa-jantung\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\laragon\www\diagnosa-jantung\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#14 C:\laragon\www\diagnosa-jantung\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#15 C:\laragon\www\diagnosa-jantung\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#16 {main}
CRITICAL - 2025-10-29 17:00:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'diagnosa_jantung.pasien' doesn't exist
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 4 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 5 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 6 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 17:00:32 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'diagnosa_jantung.pasien' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 6 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 7 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 8 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-29 17:00:32 --> [Caused by] mysqli_sql_exception: Table 'diagnosa_jantung.pasien' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `pasien`
WHERE `nik` = \'12389389278343223\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `pasien`
WHERE `nik` = :nik:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('12389389278343223', 'pasien.nik', [...])
 7 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('12389389278343223', 'pasien.nik', [...], null, 'nik')
 8 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('nik', 'nik', '12389389278343223', [...], [...], 'nik')
 9 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
10 APPPATH\Controllers\Auth.php(91): CodeIgniter\Controller->validate([...])
11 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->attemptRegister()
12 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
13 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
16 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-29 17:00:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 17:00:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 17:00:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-29 17:25:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
